# rebuild after changing this file!

# site variables
title: Ted Byron
email: ted@tedbyron.com
description: >-
  Ted Byron's Website
url: https://tedbyron.com

author: tedbyron
github_username: tedbyron
github_url: https://github.com/tedbyron
gitlab_url: https://gitlab.com/tedbyron

# build options
repository: tedbyron/tedbyron.github.io
github: [metadata]
encoding: UTF-8
future: true
jailed: false
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
gfm_quirks: paragraph_end
sass:
  load_paths: assets/_sass
  style: compressed
theme: jekyll-theme-primer

plugins:
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-tidy

# excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
