# rebuild after changing this file!

# site variables
title: Ted Byron
email: ted@tedbyron.com
description: >-
  Ted Byron's Website
url: "https://tedbyron.com"
github_username: tedbyron

# build options
repository: tedbyron/tedbyron.github.io
github: [metadata]
encoding: UTF-8
future: true
jailed: false
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
gfm_quirks: paragraph_end
sass:
  sass_dir: _scss
sass:
  style: compressed

plugins:
  - jekyll-gist
  - jekyll-seo-tag

# excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
